{% set name = "spiceypy" %}
{% set version = "4.0.2" %}
{% set sha256 = "1e7d1cdd36b620829c21233c8b89252fe5d684a0414fdc7da53a4481781a755b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - 0001-newer-single-patch-for-conda-installs.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - numpy >=1.17.0
  run:
    - python >=3.6
    - cspice ==66
    - numpy >=1.17.0

test:
  imports:
    - spiceypy
    - spiceypy.utils
  requires:
    - pytest
    - pandas
    - numpy >=1.17.0
  source_files:
    - spiceypy/tests
  commands:
    - python -m pytest spiceypy -rpP -v --verbose --tb=long

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: The NASA JPL NAIF SPICE toolkit wrapper written in Python

  description: |
    SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
    essential tool for scientists and engineers alike in the planetary
    science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
