{% set name = "spiceypy" %}
{% set version = "2.3.2" %}
{% set sha256 = "a10064b5b266e2e2363e1060c77db8653677eada0103970b47d9c75e08ba906f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - 0001-Remove-CSPICE-installation-logic.patch
    - 0002-Get-rid-of-setup_requires.patch

build:
  number: 0
  noarch: python

  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cspice ==66
    - numpy
    - six

test:
  imports:
    - spiceypy
    - spiceypy.utils
  requires:
    - pytest
    - pandas
    - numpy
  source_files:
    - spiceypy/tests
  commands:
    - python -m pytest spiceypy -rpP -v --verbose --tb=long

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: 'The NASA JPL NAIF SPICE toolkit wrapper written in Python'

  description: |
      SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
      essential tool for scientists and engineers alike in the planetary
      science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - juanlu001
    - AndrewAnnex
