{% set name = "spiceypy" %}
{% set version = "7.0.0" %}
{% set sha256 = "ac27096a12b795898c3a6d1fa1f12a7e4485f480acd2e59fbd3a986cb0ade2be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/AndrewAnnex/SpiceyPy.git
  git_rev: cyice
  git_depth: 0


build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.26                           # [build_platform != target_platform]
    - cspice ==67                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pip
  host:
    - python
    - cython
    - numpy >=1.26
    - cspice ==67
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - numpy >=1.26
    - cspice ==67


test:
  imports:
    - spiceypy
    - spiceypy.utils
    - spiceypy.cyice
  requires:
    - pytest >=7.0.0
    - pytest-benchmark
    - pandas
    - numpy >=1.26
    - cspice ==67
    - python
  commands:
    - python -m pytest --pyargs spiceypy -rpP -v --verbose --tb=long

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: The NASA JPL NAIF SPICE toolkit wrapper written in Python

  description: |
    SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
    essential tool for scientists and engineers alike in the planetary
    science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
