{% set name = "spiceypy" %}
{% set version = "6.0.0" %}
{% set sha256 = "ac27096a12b795898c3a6d1fa1f12a7e4485f480acd2e59fbd3a986cb0ade2be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - 0001-newer-single-patch-for-conda-installs.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - numpy >=1.17.0
  run:
    - python >={{ python_min }}
    - cspice ==67
    - numpy >=1.17.0

test:
  imports:
    - spiceypy
    - spiceypy.utils
  requires:
    - pytest <7.0.0
    - pandas
    - numpy >=1.17.0
    - python {{ python_min }}
  commands:
    - python -m pytest --pyargs spiceypy -rpP -v --verbose --tb=long

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: The NASA JPL NAIF SPICE toolkit wrapper written in Python

  description: |
    SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
    essential tool for scientists and engineers alike in the planetary
    science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
