# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hnhK7v62WVzdqyCCHvoWQ46eAJbtWbIhSCHUEa2XXXxc3S9q3XIT2Bt14MCiWT7KsaUwwRENTqlFeTGi0o01QZly4voWk4uKebnnclnLNkd4sTOaFdRcTBXBF6k0dO/yOJNAfiS/402mxdilKMHKkhJmV+Z5oOOMA/ozync6uUexN6c5j5kHM5ymktvw4zUeQ8iYzClxMyM3N69NKc8KnqJaN4QC1efCkhprIu+iBVgv7Zy+yDikcF+uwkOjF9prT5B+7xxjOvyJZFcZgIQvpyJx0IpvGuYknjWcV4NGlKWgF8Q3sZp60Ex3b4qxeVDcI1PKi0kzN2UQQqxl650ZGNYIWmvU1tytnuJaYWpk6PuaXSWDbDLRUQUH8rwUI+A28L/AI37ekmYNiSHTsXB2DyFPVtOpWZg/07qdRQm2MQKyrVuPxfAoadM3mf21mBiNcnCejOqP0fDPAQNlWWi6s2ZrbbWoMCoOoGksZ1veCmqUBGm5iFxdpGTPwG3DCgvUXw1fZiEaRx0Cox+4+UemWJUOCcT5BV93lsv2cWCS/z8Vx3zy0SyQHaIWLkAi1AHtznIjbq4bOFlXkYtS1ojOd3XyhzlyJwi3YfgAuJvDdxh/bFAdPAUm70GxFsBAd24mRn1pGou/fdu4/KTeLGE9pLImqh1XKQhp8vd6KhrKRN4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
