travis:
  secure:
    BINSTAR_TOKEN: hnhK7v62WVzdqyCCHvoWQ46eAJbtWbIhSCHUEa2XXXxc3S9q3XIT2Bt14MCiWT7KsaUwwRENTqlFeTGi0o01QZly4voWk4uKebnnclnLNkd4sTOaFdRcTBXBF6k0dO/yOJNAfiS/402mxdilKMHKkhJmV+Z5oOOMA/ozync6uUexN6c5j5kHM5ymktvw4zUeQ8iYzClxMyM3N69NKc8KnqJaN4QC1efCkhprIu+iBVgv7Zy+yDikcF+uwkOjF9prT5B+7xxjOvyJZFcZgIQvpyJx0IpvGuYknjWcV4NGlKWgF8Q3sZp60Ex3b4qxeVDcI1PKi0kzN2UQQqxl650ZGNYIWmvU1tytnuJaYWpk6PuaXSWDbDLRUQUH8rwUI+A28L/AI37ekmYNiSHTsXB2DyFPVtOpWZg/07qdRQm2MQKyrVuPxfAoadM3mf21mBiNcnCejOqP0fDPAQNlWWi6s2ZrbbWoMCoOoGksZ1veCmqUBGm5iFxdpGTPwG3DCgvUXw1fZiEaRx0Cox+4+UemWJUOCcT5BV93lsv2cWCS/z8Vx3zy0SyQHaIWLkAi1AHtznIjbq4bOFlXkYtS1ojOd3XyhzlyJwi3YfgAuJvDdxh/bFAdPAUm70GxFsBAd24mRn1pGou/fdu4/KTeLGE9pLImqh1XKQhp8vd6KhrKRN4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
