travis:
  secure:
    BINSTAR_TOKEN: HtwKi+TWmWdDruhjsmP5jqGDgMQEh5l7qjNXDXA1wRytiOcWPsW2dFhvXYsJ0aLpcloVitTcOV6Pe1jWVToGfHZoLYEMsPGXp1ryBHzYTXoJxrO49ELxckmehkgJAibj8H+b/evmCdF35vYft2xlKQi3uwbQi+Ry54M/WlwvdcWqli0vjLwLDijbisccSA3UI/uxTrkAsFrwNLz/HKoqhFBzuZ6FynPTWxOoW0bGlEdis3fqqvTwnype0YY31sImt/kNWQHMOmDekvIA5hISNA3WJqNODhCcdG/DpmFuVTOm5Y62aXsl01ocnrwNij/4X2IWFPCdiQu1PLoIPREGRf45iPPV1Hh8cWEezRrwL29As+NN7QJk1ZoOURmTrMDpD4ved35sN5mFfCmui6bSZDaOKH/r+fHi44MaxWK17AJSbQwLltxsdV+yBcVzOGdAZm6GtodzPg9Nz8D5dhwtFI3Xs+ZqaLH6/RcAl3xZI4Erktzkf/hZ9ZfmRzgxDLT9+plxWtihiRSpDhZ2FmpNLBaVL8mtZOArszz9fkoA5dsxcjAR0v07CG3b66jI5Ow1R0Q8J+lCM0n0Mo8iam43Xe7NnEOjFUFZqNRG1SOZVbOYoYTP+U7+CbtYPRhfbSyx9h1+ZsqI0o9AAMTujLcnu5qxZoMxSL0veXefSrQ93YE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
